version: 0.2

phases:
  install:
    commands:
      - echo Installing Docker...
      - yum install -y docker
      - service docker start
      - $(aws ecr get-login --no-include-email --region eu-north-1)
  build:
    commands:
      - echo Building Docker image...
      - docker build -t $REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - docker push $REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION
artifacts:
  files: '**/*'
  discard-paths: yes
