version: 0.2

env:
  variables:
    ImageName: "forumwedkarskie"

phases:
  install:
    runtime-versions:
      docker: 18
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $ImageName -f Dockerfile .
  post_build:
    commands:
      - echo "Build completed successfully!"
      - echo "Tagging Docker image..."
      - docker tag $ImageName:latest 514005485351.dkr.ecr.eu-north-1.amazonaws.com/forumwedkarskie:latest
      - echo "Pushing Docker image to ECR..."
      - $(aws ecr get-login --no-include-email --region eu-north-1)
      - docker push 514005485351.dkr.ecr.eu-north-1.amazonaws.com/forumwedkarskie:latest
      - echo '[ { "name": "forum-container", "imageUri": "514005485351.dkr.ecr.eu-north-1.amazonaws.com/simple-docker-service-0a18a02148e9:latest" } ]' > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
